name: Generate documentation
on:
  push:
    paths:
    - documentation-generator/**
    - docs/*.md

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install pandoc
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          pip-version: '26.0.1'
          pip-install: 'beautifulsoup4'
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Run generator
        run: documentation-generator/run.py
